# -*- coding: utf-8 -*-
"""Mentor project - fintuning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yt_xVbTYD7KT3hS5PE9Qff9z_r8ENPfP

Hard reset VRAM
"""

import gc, torch
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
gc.collect()
torch.cuda.empty_cache()

"""Install"""

!pip -q install transformers datasets accelerate peft scikit-learn pandas numpy matplotlib

"""Load dataset from local file (canonical)"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

# change filename if needed
CSV_PATH = list(uploaded.keys())[0]
df = pd.read_csv(CSV_PATH)

print("Loaded dataframe shape:", df.shape)
df.head()

"""Load CSV + train/test split"""

import random, numpy as np, pandas as pd
from datasets import Dataset
from sklearn.model_selection import train_test_split

SEED=42
random.seed(SEED); np.random.seed(SEED)

# df must already exist from your upload step
# df columns: "data" (text), "labels" (string label)
train_df, test_df = train_test_split(
    df, test_size=0.2, stratify=df["labels"], random_state=SEED
)
train_df = train_df.reset_index(drop=True)
test_df  = test_df.reset_index(drop=True)

label_names = sorted(df["labels"].unique().tolist())
label2id = {l:i for i,l in enumerate(label_names)}
id2label = {i:l for l,i in label2id.items()}

train_df["label_id"] = train_df["labels"].map(label2id)
test_df["label_id"]  = test_df["labels"].map(label2id)

ds_train = Dataset.from_pandas(train_df)
ds_test  = Dataset.from_pandas(test_df)

print("labels:", label_names)
print(ds_train, ds_test)

"""Tokenizer + SequenceClassification model"""

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_ID = "codefuse-ai/F2LLM-0.6B"  # embedding/feature-extraction model :contentReference[oaicite:1]{index=1}
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_ID,
    num_labels=len(label_names),
    id2label=id2label,
    label2id=label2id,
    device_map="auto",
)

model.to("cuda")

"""set pad_token on tokenizer + config"""

if tokenizer.eos_token is None:
    tokenizer.add_special_tokens({"eos_token": "</s>"})
if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({"pad_token": "</s>"})
model.resize_token_embeddings(len(tokenizer))
model.config.pad_token_id = tokenizer.pad_token_id

print("eos:", tokenizer.eos_token, tokenizer.eos_token_id)
print("pad:", tokenizer.pad_token, tokenizer.pad_token_id)
print("config pad_token_id:", model.config.pad_token_id)

"""gradient checkpointing"""

model.gradient_checkpointing_enable()
model.config.use_cache = False

"""Tokenize dataset"""

TEXT_COL = "data"
LABEL_COL = "label_id"

def tok(batch):
    return tokenizer(
        batch[TEXT_COL],
        truncation=True,
        max_length=256,
        padding="max_length",
    )

ds_train_tok = ds_train.map(tok, batched=True)
ds_test_tok  = ds_test.map(tok, batched=True)

cols = ["input_ids","attention_mask", LABEL_COL]
ds_train_tok = ds_train_tok.remove_columns([c for c in ds_train_tok.column_names if c not in cols])
ds_test_tok  = ds_test_tok.remove_columns([c for c in ds_test_tok.column_names if c not in cols])

ds_train_tok = ds_train_tok.rename_column(LABEL_COL, "labels")
ds_test_tok  = ds_test_tok.rename_column(LABEL_COL, "labels")

ds_train_tok.set_format("torch")
ds_test_tok.set_format("torch")

"""Attach LoRA adapters (PEFT)"""

from peft import LoraConfig, get_peft_model, TaskType

# Target modules vary by architecture; these are common for Transformer blocks.
# If you get an error "module not found", print model and adjust target_modules.
lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj","k_proj","v_proj","o_proj"],  # common; may need adjustment
)

model = get_peft_model(model, lora_config)
# ensure pad id survives PEFT wrap
model.config.pad_token_id = tokenizer.pad_token_id
if hasattr(model, "get_base_model"):
    base = model.get_base_model()
    if hasattr(base, "config"):
        base.config.pad_token_id = tokenizer.pad_token_id

model.print_trainable_parameters()

"""Sanity check"""

import torch
print("CUDA available:", torch.cuda.is_available())
print(torch.cuda.get_device_name(0))
print("Allocated GB:", torch.cuda.memory_allocated() / 1e9)
print("Reserved  GB:", torch.cuda.memory_reserved() / 1e9)

"""Train with Trainer"""

from transformers import TrainingArguments, Trainer
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "precision_macro": precision_score(labels, preds, average="macro", zero_division=0),
        "recall_macro": recall_score(labels, preds, average="macro", zero_division=0),
        "f1_macro": f1_score(labels, preds, average="macro", zero_division=0),
        "f1_weighted": f1_score(labels, preds, average="weighted", zero_division=0),
    }

args = TrainingArguments(
    output_dir="outputs_f2llm_lora",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    learning_rate=2e-4,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=50,
    bf16=True,                           # ✅ fastest stable mixed precision here
    fp16=False,

    optim="adamw_torch_fused",           # ✅ fast on GPU

    dataloader_pin_memory=True,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=ds_train_tok,
    eval_dataset=ds_test_tok,   # for quick; ideally have val split
    compute_metrics=compute_metrics,
)

trainer.train()

"""Full classification report + confusion matrix"""

from transformers import  Trainer
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

pred = trainer.predict(ds_test_tok)
y_true = pred.label_ids
y_hat  = np.argmax(pred.predictions, axis=-1)

print(classification_report(
    y_true, y_hat,
    target_names=label_names,
    digits=3, zero_division=0
))

cm = confusion_matrix(y_true, y_hat, labels=list(range(len(label_names))))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=label_names)

plt.figure(figsize=(6,6))
disp.plot(values_format="d")
plt.xticks(rotation=45, ha="right")
plt.title("F2LLM-0.6B + LoRA — Confusion Matrix")
plt.show()

"""Save adapters (LoRA weights only)"""

model.save_pretrained("f2llm_0p6b_lora_adapters")
tokenizer.save_pretrained("f2llm_0p6b_lora_adapters")